services:
  db: 
    image: mysql:8.0
    container_name: db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      # 移除MYSQL_USER配置，因为我们要使用root用户
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    # 添加上面的命令行参数以使用更兼容的认证插件
    
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    restart: always

  server:
    build: ./server
    container_name: server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    restart: always

  frontend:
    build: .
    container_name: frontend
    ports:
      - "8080:80"
      - "443:443"
    environment:
      - API_URL=https://server:3000  # 改为HTTP
    depends_on:
      - server
    restart: always