[project]
name = "mcp-pro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anthropic>=0.49.0",
    "flask>=3.1.0",
    "gunicorn>=23.0.0",
    "mcp>=1.5.0",
    "python-dotenv>=1.1.0",
]
